language: node_js
node_js:
  - 4
  - 5
  - 6

before_install:
  - npm install -g npm

after_script:
  - npm run coveralls

notifications:
  email:
    recipients:
      - d.f.ellis@ieee.org
    on_success: change
    on_failure: change
